export const categories = [
  { id: 'shiro', title: 'Shiro Tera', desc: 'Spices & Grains', img: '/images/shiro.jpg' },
  { id: 'buna', title: 'Buna Tera', desc: 'Coffee & Coffee Equipment', img: '/images/coffee.jpg' },
  { id: 'shemene', title: 'Shemene Tera', desc: 'Clothing & Textiles', img: '/images/textiles.jpg' },
  { id: 'mesob', title: 'Mesob Tera', desc: 'Baskets & Traditional Items', img: '/images/baskets.jpg' },
  { id: 'menalesh', title: 'Menalesh Tera', desc: 'Metal Works & Tools', img: '/images/metal.jpg' },
  { id: 'atikilt', title: 'Atikilt Tera', desc: 'Vegetables & Fruits', img: '/images/produce.jpg' },
  { id: 'sumale', title: 'Sumale Tera', desc: 'Recycled & Second-hand Goods', img: '/images/secondhand.jpg' },
  { id: 'electronics', title: 'Electronics Area', desc: 'Phones & Accessories', img: '/images/electronics.jpg' },
];

export const sellers = [
  { id: 'alemu-coffee', name: 'Alemu Coffee Traders', city: 'Addis Ababa', area: 'Buna Tera', rating: 4.7, tagline: 'Fresh buna, roasted daily.' },
  { id: 'tigist-crafts', name: 'Tigist Crafts', city: 'Addis Ababa', area: 'Mesob Tera', rating: 4.8, tagline: 'Handmade baskets & tradition.' },
  { id: 'shemene-textiles', name: 'Shemene Textiles', city: 'Addis Ababa', area: 'Shemene Tera', rating: 4.5, tagline: 'Cotton, patterns, and comfort.' },
  { id: 'menalesh-metals', name: 'Menalesh Metals', city: 'Addis Ababa', area: 'Menalesh Tera', rating: 4.6, tagline: 'Tools and metal works.' },
  { id: 'atikilt-coop', name: 'Atikilt Farmers Co-op', city: 'Addis Ababa', area: 'Atikilt Tera', rating: 4.4, tagline: 'Fresh produce every morning.' },
  { id: 'sumale-electro', name: 'Sumale Electronics', city: 'Addis Ababa', area: 'Electronics Area', rating: 4.2, tagline: 'Phones, accessories, repairs.' },
  { id: 'shiro-spice-house', name: 'Shiro Spice House', city: 'Addis Ababa', area: 'Shiro Tera', rating: 4.9, tagline: 'Berbere, mitmita, and more.' },
  { id: 'merkato-reuse', name: 'Merkato Reuse', city: 'Addis Ababa', area: 'Sumale Tera', rating: 4.1, tagline: 'Second-hand gems at fair prices.' },
];

export function getCategoryById(id) {
  return categories.find((c) => c.id === id);
}

export function getSellerById(id) {
  return sellers.find((s) => s.id === id);
}

export const products = [
  {
    id: 'p1',
    name: 'Buna Chebsa Coffee Beans',
    priceETB: 450,
    seller: 'Alemu Coffee Traders',
    sellerId: 'alemu-coffee',
    teraId: 'buna',
    section: 'Buna Tera',
    description: 'Freshly roasted Ethiopian coffee beans from Sidama.',
    stock: 24,
    imageUrl: '/images/coffee-beans.jpg',
    rating: 4.8,
    popular: true,
  },
  {
    id: 'p2',
    name: 'Handwoven Mesob Basket',
    priceETB: 1200,
    seller: 'Tigist Crafts',
    sellerId: 'tigist-crafts',
    teraId: 'mesob',
    section: 'Mesob Tera',
    description: 'Traditional handwoven basket ideal for serving food.',
    stock: 5,
    imageUrl: '/images/mesob.jpg',
    rating: 4.9,
  },
  {
    id: 'p3',
    name: 'Shemema Cotton Shawl',
    priceETB: 800,
    seller: 'Shemene Textiles',
    sellerId: 'shemene-textiles',
    teraId: 'shemene',
    section: 'Shemene Tera',
    description: 'Soft cotton shawl with traditional patterns.',
    stock: 12,
    imageUrl: '/images/shawl.jpg',
    rating: 4.6,
    popular: true,
  },
  {
    id: 'p4',
    name: 'Metal Coffee Pot (Jebena)',
    priceETB: 650,
    seller: 'Menalesh Metals',
    sellerId: 'menalesh-metals',
    teraId: 'menalesh',
    section: 'Menalesh Tera',
    description: 'Sturdy traditional coffee pot for brewing buna.',
    stock: 8,
    imageUrl: '/images/jebena.jpg',
    rating: 4.4,
  },
  {
    id: 'p5',
    name: 'Fresh Atikilt Tomatoes (1kg)',
    priceETB: 60,
    seller: 'Atikilt Farmers Co-op',
    sellerId: 'atikilt-coop',
    teraId: 'atikilt',
    section: 'Atikilt Tera',
    description: 'Locally grown ripe tomatoes.',
    stock: 200,
    imageUrl: '/images/tomatoes.jpg',
    rating: 4.3,
  },
  {
    id: 'p6',
    name: 'Used Smartphone - Good Condition',
    priceETB: 3500,
    seller: 'Sumale Electronics',
    sellerId: 'sumale-electro',
    teraId: 'electronics',
    section: 'Electronics Area',
    description: 'Pre-owned smartphone unlocked, 64GB.',
    stock: 3,
    imageUrl: '/images/phone.jpg',
    rating: 4.1,
  },
  {
    id: 'p7',
    name: 'Mitmita (Spicy Chili Blend) 250g',
    priceETB: 180,
    seller: 'Shiro Spice House',
    sellerId: 'shiro-spice-house',
    teraId: 'shiro',
    section: 'Shiro Tera',
    description: 'Hot, aromatic mitmita blend — perfect for kitfo and tibs.',
    stock: 90,
    imageUrl: '/images/mitmita.jpg',
    rating: 4.8,
    popular: true,
  },
  {
    id: 'p8',
    name: 'Berbere (Premium) 500g',
    priceETB: 260,
    seller: 'Shiro Spice House',
    sellerId: 'shiro-spice-house',
    teraId: 'shiro',
    section: 'Shiro Tera',
    description: 'Rich berbere with deep color and fragrance — slow roasted spices.',
    stock: 120,
    imageUrl: '/images/berbere.jpg',
    rating: 4.9,
    popular: true,
  },
  {
    id: 'p9',
    name: 'Green Coffee Beans (Raw) 1kg',
    priceETB: 520,
    seller: 'Alemu Coffee Traders',
    sellerId: 'alemu-coffee',
    teraId: 'buna',
    section: 'Buna Tera',
    description: 'Unroasted green beans for home roasting — Yirgacheffe origin.',
    stock: 40,
    imageUrl: '/images/green-coffee.jpg',
    rating: 4.5,
  },
  {
    id: 'p10',
    name: 'Jebena Clay Pot (Traditional)',
    priceETB: 980,
    seller: 'Menalesh Metals',
    sellerId: 'menalesh-metals',
    teraId: 'menalesh',
    section: 'Menalesh Tera',
    description: 'Traditional jebena style — durable, heat-safe, perfect for buna ceremony.',
    stock: 14,
    imageUrl: '/images/jebena-clay.jpg',
    rating: 4.4,
  },
  {
    id: 'p11',
    name: 'Handcrafted Mesob (Large)',
    priceETB: 1900,
    seller: 'Tigist Crafts',
    sellerId: 'tigist-crafts',
    teraId: 'mesob',
    section: 'Mesob Tera',
    description: 'Large mesob basket, bright colors, handwoven by local artisans.',
    stock: 6,
    imageUrl: '/images/mesob-large.jpg',
    rating: 4.7,
    popular: true,
  },
  {
    id: 'p12',
    name: 'Gabi Blanket (Cotton, White)',
    priceETB: 1500,
    seller: 'Shemene Textiles',
    sellerId: 'shemene-textiles',
    teraId: 'shemene',
    section: 'Shemene Tera',
    description: 'Warm gabi blanket for evenings and celebrations — soft, traditional weave.',
    stock: 10,
    imageUrl: '/images/gabi.jpg',
    rating: 4.6,
  },
  {
    id: 'p13',
    name: 'Atikilt Potatoes (2kg)',
    priceETB: 140,
    seller: 'Atikilt Farmers Co-op',
    sellerId: 'atikilt-coop',
    teraId: 'atikilt',
    section: 'Atikilt Tera',
    description: 'Fresh potatoes — clean and sorted.',
    stock: 160,
    imageUrl: '/images/potatoes.jpg',
    rating: 4.2,
  },
  {
    id: 'p14',
    name: 'Atikilt Avocado (3pcs)',
    priceETB: 120,
    seller: 'Atikilt Farmers Co-op',
    sellerId: 'atikilt-coop',
    teraId: 'atikilt',
    section: 'Atikilt Tera',
    description: 'Ripe avocados — creamy and fresh.',
    stock: 80,
    imageUrl: '/images/avocado.jpg',
    rating: 4.5,
    popular: true,
  },
  {
    id: 'p15',
    name: 'USB-C Fast Charger (Original)',
    priceETB: 420,
    seller: 'Sumale Electronics',
    sellerId: 'sumale-electro',
    teraId: 'electronics',
    section: 'Electronics Area',
    description: 'Fast charging adapter with safety protection.',
    stock: 55,
    imageUrl: '/images/charger.jpg',
    rating: 4.3,
  },
  {
    id: 'p16',
    name: 'Wireless Earbuds (Budget)',
    priceETB: 950,
    seller: 'Sumale Electronics',
    sellerId: 'sumale-electro',
    teraId: 'electronics',
    section: 'Electronics Area',
    description: 'Comfort fit, decent bass — great for calls and music.',
    stock: 18,
    imageUrl: '/images/earbuds.jpg',
    rating: 4.0,
  },
  {
    id: 'p17',
    name: 'Second-hand Winter Jacket (Grade A)',
    priceETB: 900,
    seller: 'Merkato Reuse',
    sellerId: 'merkato-reuse',
    teraId: 'sumale',
    section: 'Sumale Tera',
    description: 'Clean grade-A winter jacket — warm and stylish.',
    stock: 7,
    imageUrl: '/images/jacket.jpg',
    rating: 4.1,
  },
  {
    id: 'p18',
    name: 'Second-hand Cooking Pot Set',
    priceETB: 1100,
    seller: 'Merkato Reuse',
    sellerId: 'merkato-reuse',
    teraId: 'sumale',
    section: 'Sumale Tera',
    description: 'Used pot set in good condition — cleaned and checked.',
    stock: 4,
    imageUrl: '/images/pots.jpg',
    rating: 4.0,
  },
];
